title: CLAS 205
description: Autumn 2024
theme: just-the-docs

url: https://clas-205.github.io/au24-site/

aux_links:
  Gradescope: https://www.gradescope.com/account
  Canvas: canvas.uw.edu

aux_links_new_tab: true

nav_enabled: true

footer_content: "Suh Young Choi &copy; 2024 <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY-NC-SA 4.0</a>"